"""
Unit tests for city clustering analysis helpers.
"""

import pandas as pd
import pytest

from src.analysis.city_clustering import (
    DEFAULT_CLUSTERING_FEATURES,
    build_same_cluster_peer_table,
    cluster_cities,
    compare_cities_in_same_cluster,
)


def _build_city_df(rows):
    columns = [
        "municipality_code",
        "municipality_name",
        "state_code",
        "state_name",
        "cluster",
        *DEFAULT_CLUSTERING_FEATURES,
    ]
    return pd.DataFrame(rows, columns=columns)


def _fill_features(value: float):
    return [value] * len(DEFAULT_CLUSTERING_FEATURES)


def test_cluster_cities_selects_best_k_and_adds_cluster_column():
    """Automatic K selection should produce two clear clusters in synthetic data."""
    rows = []
    base_vectors = [0.0, 0.1, -0.1, 5.0, 5.1, 4.9]
    for idx, value in enumerate(base_vectors, start=1):
        feature_values = _fill_features(value)
        rows.append(
            [
                f"{idx:07d}",
                f"City {idx}",
                "35" if idx <= 3 else "41",
                "Sao Paulo" if idx <= 3 else "Parana",
                -1,
                *feature_values,
            ]
        )
    df = _build_city_df(rows)
    df = df.drop(columns=["cluster"])  # cluster is generated by helper

    result = cluster_cities(df, min_k=2, max_k=3, random_state=42)

    assert "cluster" in result.clustered_df.columns
    assert result.selected_k == 2
    assert result.clustered_df["cluster"].nunique() == 2
    assert result.silhouette > 0
    assert list(result.diagnostics["k"]) == [2, 3]


def test_compare_cities_in_same_cluster_returns_ranked_peers():
    """A city should return nearest peers from its own cluster ordered by distance."""
    rows = [
        ["0000001", "Alpha", "35", "Sao Paulo", 0, *_fill_features(0.0)],
        ["0000002", "Beta", "35", "Sao Paulo", 0, *_fill_features(0.2)],
        ["0000003", "Gamma", "35", "Sao Paulo", 0, *_fill_features(0.5)],
        ["0000004", "Delta", "41", "Parana", 1, *_fill_features(5.0)],
        ["0000005", "Epsilon", "41", "Parana", 1, *_fill_features(5.3)],
    ]
    df = _build_city_df(rows)

    peers = compare_cities_in_same_cluster(df, municipality_code="0000001", top_n=2)

    assert len(peers) == 2
    assert list(peers["peer_rank"]) == [1, 2]
    assert peers.iloc[0]["peer_municipality_name"] == "Beta"
    assert peers.iloc[1]["peer_municipality_name"] == "Gamma"
    assert peers.iloc[0]["distance"] < peers.iloc[1]["distance"]


def test_compare_cities_in_same_cluster_raises_for_ambiguous_city_name():
    """Repeated city names require state_code or municipality_code disambiguation."""
    rows = [
        ["0000001", "Santa Maria", "43", "Rio Grande do Sul", 0, *_fill_features(0.0)],
        ["0000002", "Santa Maria", "29", "Bahia", 0, *_fill_features(0.1)],
        ["0000003", "Porto Alegre", "43", "Rio Grande do Sul", 0, *_fill_features(0.2)],
    ]
    df = _build_city_df(rows)

    with pytest.raises(ValueError, match="ambiguous"):
        compare_cities_in_same_cluster(df, city_name="Santa Maria", top_n=1)


def test_build_same_cluster_peer_table_returns_top_n_for_each_city():
    """Bulk peer table should include one nearest peer per city when top_n=1."""
    rows = [
        ["0000001", "Alpha", "35", "Sao Paulo", 0, *_fill_features(0.0)],
        ["0000002", "Beta", "35", "Sao Paulo", 0, *_fill_features(0.2)],
        ["0000003", "Gamma", "35", "Sao Paulo", 0, *_fill_features(0.5)],
        ["0000004", "Delta", "41", "Parana", 1, *_fill_features(5.0)],
        ["0000005", "Epsilon", "41", "Parana", 1, *_fill_features(5.3)],
    ]
    df = _build_city_df(rows)

    peer_table = build_same_cluster_peer_table(df, top_n=1)

    assert len(peer_table) == len(df)
    assert peer_table["peer_rank"].nunique() == 1
    assert int(peer_table["peer_rank"].iloc[0]) == 1
    assert (peer_table["source_municipality_code"] != peer_table["peer_municipality_code"]).all()
